version: '3.5'
services:
  php:
    image: schmittphill/etsp:latest
    restart: always
    ports:
      - 8000:80
    environment:
      - APP_KEY="base64:ENfg+X/DKXAEIN3QpDXXisEFkGXzrXJtxcXuTLzcq48="
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_PORT=3306
      - DB_HOST=mysql
      - DB_DATABASE=db_etsp
      - DB_USERNAME=root
      - DB_PASSWORD=admin
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}